import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import axios from 'axios'
import moment from 'moment'
import Home from '../components/Home'


export default function HomePage({posts}) {
  const router = useRouter()

    useEffect(() => {
      // const fetchData = async () => {
      //   try{
      //     const res = await axios.get(`http://localhost:4000/api/posts`)
      //     setPosts(res.data)
      //   }catch (err) {
      //     console.log(err)
      //   }
      // }
      // fetchData()
    // let token = sessionStorage.getItem("Token");
    // if (!token) {
    //   router.push("/login");
    // }
    // setTimeout(() => {
    //   setLoading(true);
    // }, 500)
  } );
  return (
    <div>
      <Head>
        <title>Aerosmart Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Header/>
      <Home posts={posts} />
     <Footer />
     </main>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const res = await axios.get(process.env.NEXT_PUBLIC_POST_URL)
  const posts =  await res.data

  return {
      props: {
          posts: posts.slice(0, 10)
      }
  }
}

